# Generated by Django 2.0.1 on 2018-02-16 23:22

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True)),
                ('title', models.CharField(default='', max_length=20, unique=True)),
                ('slug', models.SlugField(default='', unique=True)),
                ('description', models.CharField(default='', max_length=250)),
                ('context', models.CharField(default='', max_length=100)),
                ('key_takeaways', models.CharField(default='', max_length=50)),
                ('sample_uses_and_visualization', models.CharField(default='', max_length=100)),
                ('technical_details', models.CharField(default='', max_length=100)),
                ('applicable_models', models.CharField(default='', max_length=100)),
                ('relevant_publications', models.CharField(default='', max_length=50)),
                ('contact_details', models.EmailField(default='example@gmail.com', max_length=50)),
                ('owner', models.CharField(default='', max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DataSetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True)),
                ('title', models.CharField(default='', max_length=20, unique=True)),
                ('slug', models.SlugField(default='', unique=True)),
                ('description', models.CharField(default='', max_length=250)),
                ('context', models.CharField(default='', max_length=100)),
                ('key_takeaways', models.CharField(default='', max_length=50)),
                ('sample_uses_and_visualization', models.CharField(default='', max_length=100)),
                ('technical_details', models.CharField(default='', max_length=100)),
                ('applicable_models', models.CharField(default='', max_length=100)),
                ('relevant_publications', models.CharField(default='', max_length=50)),
                ('contact_details', models.EmailField(default='example@gmail.com', max_length=50)),
                ('owner', models.CharField(default='', max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Well Being', 'Well Being'), ('Health', 'Health'), ('Environment', 'Environment'), ('Equity', 'Equity'), ('Livability', 'Livability')], default='', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Social', 'Social'), ('Environment', 'Environment'), ('Infrastructure', 'Infrastructure'), ('Urban Design', 'Urban Design')], default='', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Intra City Data', 'Intra City Data'), ('Whole City Data', 'Whole City Data'), ('All City Data', 'All City Data')], default='', max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='outcomes',
            field=models.ManyToManyField(to='data.Outcome'),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='parameters',
            field=models.ManyToManyField(to='data.Parameter'),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='scales',
            field=models.ManyToManyField(to='data.Scale'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='outcomes',
            field=models.ManyToManyField(to='data.Outcome'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='parameters',
            field=models.ManyToManyField(to='data.Parameter'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='scales',
            field=models.ManyToManyField(to='data.Scale'),
        ),
    ]
