# Generated by Django 2.0.1 on 2018-02-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='datasetmodel',
            name='publish',
        ),
        migrations.AddField(
            model_name='dataset',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
