# Generated by Django 2.0.1 on 2018-02-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='applicable_models',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='contact_details',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='context',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='key_takeaways',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='owner',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='relevant_publications',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='sample_uses_and_visualization',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='technical_details',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='title',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
