# Generated by Django 2.0.1 on 2018-02-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='title',
            field=models.CharField(blank=True, choices=[('Dataset', 'Dataset'), ('Model', 'Model')], default='', max_length=10, unique=True),
        ),
    ]
