# Generated by Django 2.0.1 on 2018-02-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='publish',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='publish',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default='True'),
        ),
    ]
