# Generated by Django 2.0.1 on 2018-02-17 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180217_0030'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dataset',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='datasetmodel',
            managers=[
            ],
        ),
    ]
