# Generated by Django 2.0.1 on 2018-02-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180216_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='publish',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='publish',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10),
        ),
    ]
