# Generated by Django 2.0.1 on 2018-02-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180219_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='type',
            field=models.CharField(default='Dataset', max_length=10),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='type',
            field=models.CharField(default='Model', max_length=10),
        ),
    ]
