# Generated by Django 2.0.1 on 2018-03-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20180319_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuresmodeling',
            name='title',
            field=models.CharField(blank=True, choices=[('Historical Data', 'Historical Data'), ('Base Year Data', 'Base Year Data'), ('Futures Modeling Data', 'Futures Modeling Data')], default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='title',
            field=models.CharField(blank=True, choices=[('One Time Assessment', 'One Time Assessment'), ('Time Series', 'Time Series')], default='', max_length=20, unique=True),
        ),
    ]
