# Generated by Django 2.0.1 on 2018-02-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20180219_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='type',
            field=models.CharField(choices=[('Dataset', 'Dataset'), ('Model', 'Model')], default='Dataset', max_length=10),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='type',
            field=models.CharField(choices=[('Dataset', 'Dataset'), ('Model', 'Model')], default='Model', max_length=10),
        ),
    ]
