# Generated by Django 2.0.1 on 2018-02-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20180216_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='status',
        ),
        migrations.RemoveField(
            model_name='datasetmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='dataset',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
