# Generated by Django 2.0.1 on 2018-02-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20180219_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Dataset', 'Dataset'), ('Model', 'Model')], default='Dataset', max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='applicable_models',
            new_name='applicable_models_or_datasets',
        ),
        migrations.RenameField(
            model_name='datasetmodel',
            old_name='applicable_models',
            new_name='applicable_models_or_datasets',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='type',
        ),
        migrations.RemoveField(
            model_name='datasetmodel',
            name='type',
        ),
        migrations.AddField(
            model_name='dataset',
            name='type',
            field=models.ManyToManyField(to='data.Type'),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='type',
            field=models.ManyToManyField(to='data.Type'),
        ),
    ]
