# Generated by Django 2.0.1 on 2018-03-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20180319_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuresmodeling',
            name='title',
            field=models.CharField(blank=True, choices=[('Historical Data', 'Historical Data'), ('Base Year Data', 'Base Year Data'), ('Futures Modeling Data', 'Futures Modeling Data')], default='', max_length=25, unique=True),
        ),
    ]
