# Generated by Django 2.0.1 on 2018-05-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20180319_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='title',
            field=models.CharField(blank=True, choices=[('Intra Urban', 'Intra Urban'), ('Whole City', 'Whole City'), ('National Urban', 'National Urban')], default='', max_length=20, unique=True),
        ),
    ]
