# Generated by Django 2.0.1 on 2018-02-21 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20180221_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='datasetmodel',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='type',
        ),
        migrations.AddField(
            model_name='dataset',
            name='type',
            field=models.ForeignKey(default='Dataset', on_delete=django.db.models.deletion.CASCADE, to='data.Type'),
        ),
        migrations.RemoveField(
            model_name='datasetmodel',
            name='type',
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='type',
            field=models.ForeignKey(default='Dataset', on_delete=django.db.models.deletion.CASCADE, to='data.Type'),
        ),
    ]
