# Generated by Django 2.0.1 on 2018-02-16 22:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20180216_2214'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dataset',
            managers=[
                ('publishe', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='datasetmodel',
            managers=[
                ('publishe', django.db.models.manager.Manager()),
            ],
        ),
    ]
