# Generated by Django 2.0.1 on 2018-05-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20180504_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='scales',
            new_name='spatial_scales',
        ),
    ]
