# Generated by Django 2.0.1 on 2018-02-21 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20180221_0238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataSet',
            new_name='Data',
        ),
        migrations.RemoveField(
            model_name='datasetmodel',
            name='outcomes',
        ),
        migrations.RemoveField(
            model_name='datasetmodel',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='datasetmodel',
            name='scales',
        ),
        migrations.RemoveField(
            model_name='datasetmodel',
            name='type',
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ('title',)},
        ),
        migrations.DeleteModel(
            name='DataSetModel',
        ),
    ]
