# Generated by Django 2.0.1 on 2018-05-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20180504_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='time',
            new_name='temporal_scales',
        ),
        migrations.AlterField(
            model_name='time',
            name='title',
            field=models.CharField(blank=True, choices=[('Snapshot', 'Snapshot'), ('Time Series', 'Time Series')], default='', max_length=20, unique=True),
        ),
    ]
