# Generated by Django 2.0.1 on 2018-02-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20180216_2220'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dataset',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='datasetmodel',
            managers=[
            ],
        ),
    ]
