# Generated by Django 2.0.1 on 2018-02-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20180216_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
